import { BoardData } from "./board.js";

// Adding the correct spangram path from the image
// The yellow path that spells CARDIOLOGY
export const spangramCoords = [
    [0, 1], // C
    [0, 2], // A
    [0, 3], // R
    [0, 4], // D
    [2, 4], // I
    [3, 4], // O
    [4, 4], // L
    [4, 5], // O
    [4, 6], // G
    [4, 7]  // Y
];

export const cardiologyBoard: BoardData = {
    printDate: new Date().toISOString().split("T")[0],
    id: 999,
    editor: "Custom Editor",
    constructors: "Custom Constructor",
    spangram: "CARDIOLOGY",
    clue: "The rhythm of life",
    startingBoard: [
        "HCARTS",
        "EATDOY",
        "ORDILS",
        "LTIOEE",  // Fixed from LTIOLE to match the image
        "ESALVC",
        "STOLRO",
        "NEGANO",
        "TYVYRA"  // Fixed from TVYROA to match the image
    ],
    solutions: [
        // Theme words and spangram
        "CARDIOLOGY", // Spangram
        "STENT",
        "VALVE",
        "SYSTOLE",
        "DIASTOLE",
        "HEART",
        "CORONARY",
        
        // Non-theme words (4+ letters only, no duplicates of theme words)
        "ARTS",
        "CART",
        "CARTS",
        "DATE",
        "DATES",
        "DEAL",
        "DEALS",
        "DIET",
        "DOTE",
        "DOTS",
        "DOST",
        "DOLE",
        "DOLES",
        "DYER",
        "DYES",
        "DOSE",
        "EAST",
        "EATS",
        "EASY",
        "EVIL",
        "GEAR",
        "GALE",
        "GALES",
        "GATE",
        "GATES",
        "GONE",
        "HATE",
        "HATES",
        "HAST",
        "HALO",
        "HALOS",
        "LATE",
        "LATER",
        "LAST",
        "LASTS",
        "LEAN",
        "LEANS",
        "LEST",
        "LENT",
        "LEVY",
        "LIAR",
        "LIARS",
        "LIVE",
        "LIVES",
        "LORE",
        "LORD",
        "LORDS",
        "LOSE",
        "LOST",
        "LOTS",
        "LIST",
        "LISTS",
        "LOVE",
        "LOVES",
        "NEAT",
        "NEAR",
        "NEST",
        "NESTS",
        "NOTE",
        "NOTES",
        "NOSE",
        "NOSES",
        "ORGY",
        "ORAL",
        "OVAL",
        "OVALS",
        "RATE",
        "RATES",
        "RATS",
        "RAVE",
        "RAVES",
        "REAL",
        "RITE",
        "RITES",
        "RIOT",
        "RIOTS",
        "RISE",
        "RISES",
        "RILE",
        "RILES",
        "ROLE",
        "ROLES",
        "ROLL",
        "ROLLS",
        "ROTE",
        "ROVE",
        "ROVES",
        "SALE",
        "SALES",
        "SALT",
        "SALTS",
        "SAVE",
        "SAVES",
        "SEAT",
        "SEAL",
        "SEALS",
        "SEAS",
        "SEND",
        "SENT",
        "SILT",
        "SOIL",
        "SOLE",
        "SOLVE",
        "SORT",
        "SORTS",
        "STAR",
        "STARS",
        "STARE",
        "STARES",
        "STORE",
        "STORES",
        "STOVE",
        "STOVES",
        "TALE",
        "TALES",
        "TILE",
        "TILES",
        "TOIL",
        "TORN",
        "TORE",
        "VEAL",
        "VEIL",
        "VEILS",
        "VILE",
        "VISE",
        "VOLE",
        "VOLES",
        "VOTE",
        "VOTES",
        "YEAR",
        "YEARS"
    ],
    themeCoords: {
        "CARDIOLOGY": spangramCoords,
        "STENT": [[1, 5], [0, 5], [7, 4], [6, 5], [7, 6]],
        "VALVE": [[7, 2], [6, 3], [4, 4], [4, 3], [4, 2]],
        "SYSTOLE": [[5, 5], [2, 5], [5, 4], [5, 3], [4, 3], [3, 3], [3, 4]],
        "DIASTOLE": [[2, 1], [2, 2], [6, 2], [5, 2], [0, 3], [5, 3], [3, 3], [4, 2]],
        "HEART": [[0, 0], [1, 0], [6, 0], [2, 0], [0, 3]],
        "CORONARY": [[5, 5], [5, 6], [5, 4], [5, 3], [6, 3], [6, 4], [2, 5], [7, 5]]
    }
}; 